#gt915 touchpanel driver

EXTRA_CFLAGS += $(call cc-disable-warning, date-time)

obj-$(CONFIG_GT9XX_TOUCHSCREEN_GT9XX_v28)	+= gt9xx.o
obj-$(CONFIG_GT9XX_TOUCHSCREEN_GT9XX_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_GT9XX_TOUCHSCREEN_GT9XX_TOOL)	+= goodix_tool.o
